- id: zizmor
  name: zizmor
  description: "Find security issues in GitHub Actions CI/CD setups"
  language: python
  language_version: "3.10"
  types: [yaml]
  files: (\.github/(workflows/.*|dependabot.ya?ml))|(action\.ya?ml)$
  require_serial: true
  entry: zizmor
  args:
    - "--no-progress" # https://github.com/zizmorcore/zizmor/issues/582
